/* kern benchmarks: B(name) per line */
B(matmul_naive)
B(matmul_blocked)
B(fft_radix2)
B(stencil_2d)
B(spectral_norm)
B(nbody)
B(mandelbrot)
B(sieve_primes)
B(crc32)
B(base64)
B(sha256)
B(lz_match)
B(rle_codec)
