/* alg benchmarks: B(name) per line */
B(sort_quick)
B(sort_merge)
B(sort_heap)
B(sort_radix)
B(sort_qsort)
B(sort_small)
B(sort_strings)
B(search_binary)
B(search_substring)
B(graph_bfs)
B(graph_dfs)
B(graph_dijkstra)
B(dp_edit_distance)
B(dp_knapsack)
B(backtrack_nqueens)
